# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/blue/workspace/TmingEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/blue/workspace/TmingEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Devel\" \"Unspecified\" \"assimp-dev\" \"libassimp5.0.0-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blue/workspace/TmingEngine/CMakeFiles /home/blue/workspace/TmingEngine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blue/workspace/TmingEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f src/ThirdParty/glad/CMakeFiles/glad.dir/build.make src/ThirdParty/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named lua

# Build rule for target.
lua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lua
.PHONY : lua

# fast build rule for target.
lua/fast:
	$(MAKE) -f src/ThirdParty/Lua/CMakeFiles/lua.dir/build.make src/ThirdParty/Lua/CMakeFiles/lua.dir/build
.PHONY : lua/fast

#=============================================================================
# Target rules for targets named Box2D

# Build rule for target.
Box2D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Box2D
.PHONY : Box2D

# fast build rule for target.
Box2D/fast:
	$(MAKE) -f src/ThirdParty/Box2D/CMakeFiles/Box2D.dir/build.make src/ThirdParty/Box2D/CMakeFiles/Box2D.dir/build
.PHONY : Box2D/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) -f src/ThirdParty/glm/CMakeFiles/glm.dir/build.make src/ThirdParty/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) -f src/ThirdParty/Assimp/contrib/zlib/CMakeFiles/zlibstatic.dir/build.make src/ThirdParty/Assimp/contrib/zlib/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f src/ThirdParty/Assimp/contrib/zlib/CMakeFiles/zlib.dir/build.make src/ThirdParty/Assimp/contrib/zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named IrrXML

# Build rule for target.
IrrXML: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IrrXML
.PHONY : IrrXML

# fast build rule for target.
IrrXML/fast:
	$(MAKE) -f src/ThirdParty/Assimp/contrib/irrXML/CMakeFiles/IrrXML.dir/build.make src/ThirdParty/Assimp/contrib/irrXML/CMakeFiles/IrrXML.dir/build
.PHONY : IrrXML/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) -f src/ThirdParty/Assimp/code/CMakeFiles/assimp.dir/build.make src/ThirdParty/Assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named ImGui

# Build rule for target.
ImGui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImGui
.PHONY : ImGui

# fast build rule for target.
ImGui/fast:
	$(MAKE) -f src/ThirdParty/ImGui/CMakeFiles/ImGui.dir/build.make src/ThirdParty/ImGui/CMakeFiles/ImGui.dir/build
.PHONY : ImGui/fast

#=============================================================================
# Target rules for targets named stb

# Build rule for target.
stb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stb
.PHONY : stb

# fast build rule for target.
stb/fast:
	$(MAKE) -f src/ThirdParty/Stb_Image/CMakeFiles/stb.dir/build.make src/ThirdParty/Stb_Image/CMakeFiles/stb.dir/build
.PHONY : stb/fast

#=============================================================================
# Target rules for targets named releasable

# Build rule for target.
releasable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 releasable
.PHONY : releasable

# fast build rule for target.
releasable/fast:
	$(MAKE) -f src/ThirdParty/yaml/CMakeFiles/releasable.dir/build.make src/ThirdParty/yaml/CMakeFiles/releasable.dir/build
.PHONY : releasable/fast

#=============================================================================
# Target rules for targets named debuggable

# Build rule for target.
debuggable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debuggable
.PHONY : debuggable

# fast build rule for target.
debuggable/fast:
	$(MAKE) -f src/ThirdParty/yaml/CMakeFiles/debuggable.dir/build.make src/ThirdParty/yaml/CMakeFiles/debuggable.dir/build
.PHONY : debuggable/fast

#=============================================================================
# Target rules for targets named yaml-cpp

# Build rule for target.
yaml-cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yaml-cpp
.PHONY : yaml-cpp

# fast build rule for target.
yaml-cpp/fast:
	$(MAKE) -f src/ThirdParty/yaml/CMakeFiles/yaml-cpp.dir/build.make src/ThirdParty/yaml/CMakeFiles/yaml-cpp.dir/build
.PHONY : yaml-cpp/fast

#=============================================================================
# Target rules for targets named TextEditor

# Build rule for target.
TextEditor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TextEditor
.PHONY : TextEditor

# fast build rule for target.
TextEditor/fast:
	$(MAKE) -f src/ThirdParty/TextEditor/CMakeFiles/TextEditor.dir/build.make src/ThirdParty/TextEditor/CMakeFiles/TextEditor.dir/build
.PHONY : TextEditor/fast

#=============================================================================
# Target rules for targets named ImNodes

# Build rule for target.
ImNodes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImNodes
.PHONY : ImNodes

# fast build rule for target.
ImNodes/fast:
	$(MAKE) -f src/ThirdParty/ImNodes/CMakeFiles/ImNodes.dir/build.make src/ThirdParty/ImNodes/CMakeFiles/ImNodes.dir/build
.PHONY : ImNodes/fast

#=============================================================================
# Target rules for targets named angelscript

# Build rule for target.
angelscript: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 angelscript
.PHONY : angelscript

# fast build rule for target.
angelscript/fast:
	$(MAKE) -f src/ThirdParty/Angelscript/sdk/angelscript/projects/cmake/CMakeFiles/angelscript.dir/build.make src/ThirdParty/Angelscript/sdk/angelscript/projects/cmake/CMakeFiles/angelscript.dir/build
.PHONY : angelscript/fast

#=============================================================================
# Target rules for targets named TmingEngine

# Build rule for target.
TmingEngine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TmingEngine
.PHONY : TmingEngine

# fast build rule for target.
TmingEngine/fast:
	$(MAKE) -f src/Engine/CMakeFiles/TmingEngine.dir/build.make src/Engine/CMakeFiles/TmingEngine.dir/build
.PHONY : TmingEngine/fast

#=============================================================================
# Target rules for targets named Editor

# Build rule for target.
Editor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Editor
.PHONY : Editor

# fast build rule for target.
Editor/fast:
	$(MAKE) -f src/Editor/CMakeFiles/Editor.dir/build.make src/Editor/CMakeFiles/Editor.dir/build
.PHONY : Editor/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... glad"
	@echo "... lua"
	@echo "... Box2D"
	@echo "... glm"
	@echo "... zlibstatic"
	@echo "... zlib"
	@echo "... IrrXML"
	@echo "... assimp"
	@echo "... ImGui"
	@echo "... stb"
	@echo "... releasable"
	@echo "... debuggable"
	@echo "... yaml-cpp"
	@echo "... TextEditor"
	@echo "... ImNodes"
	@echo "... angelscript"
	@echo "... TmingEngine"
	@echo "... Editor"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

